# based on https://github.com/devcontainers/images/tree/main/src/cpp
# [Choice (Only allowing Ubuntu distribution)] Ubuntu version (use Ubuntu 18.04/21.04 on local arm64/Apple Silicon): ubuntu-22.04, ubuntu-21.04, ubuntu-20.04, ubuntu-18.04
ARG VARIANT=ubuntu-22.04
FROM mcr.microsoft.com/vscode/devcontainers/cpp:${VARIANT}

# This Dockerfile exists a non-root 'vscode' user with sudo access. However, for Linux,
# this user's GID/UID must match your local user UID/GID to avoid permission issues
# with bind mounts. Update USER_UID / USER_GID if yours is not 1000. See
# https://aka.ms/vscode-remote/containers/non-root-user for details.
ARG USERNAME="vscode"
RUN mkdir -p /workspaces && chown ${USERNAME}:${USERNAME} /workspaces /home/${USERNAME}

# Uncomment the below to create a new user different from 'vscode'
# RUN set -ex \
#     useradd --uid $USER_UID --gid $USER_GID -m $USERNAME \
#     &&  groupadd --gid $USER_GID $USERNAME \
#     #
#     # [Optional] Add sudo support. Omit if you don't need to install software after connecting.
#     && apt-get update \
#     && apt-get install -y sudo \
#     && echo $USERNAME ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$USERNAME \
#     && chmod 0440 /etc/sudoers.d/$USERNAME

USER ${USERNAME}
