# based on https://github.com/devcontainers/images/tree/main/src/cpp
# [Choice (Only allowing Ubuntu distribution)] Ubuntu version (use Ubuntu 18.04/21.04 on local arm64/Apple Silicon): ubuntu-22.04, ubuntu-21.04, ubuntu-20.04, ubuntu-18.04
ARG VARIANT=ubuntu-22.04
FROM mcr.microsoft.com/vscode/devcontainers/cpp:${VARIANT}
